export enum ErrorCode {
  DUPLICATE_XPUB = 'DUPLICATE_XPUB',
  DUPLICATE_DERIVATION_PATH = 'DUPLICATE_DERIVATION_PATH',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  NOT_FOUND = 'NOT_FOUND',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
